version: "3.8"

services:
  focalboard:
    image: mattermost/focalboard
    container_name: focalboard
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - focalboard-data:/opt/focalboard/data

volumes:
  focalboard-data: